const Classes = [
    { title:'PSYCHO TRAINING',
      id:1,
      img:'https://i.ibb.co/yP24SHf/victor-freitas-546919-unsplash.png',
      description:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in',
      day1:'Monday',
      time1:'8.00 AM - 9.00 AM',
      day1:'Tuesday',
      time1:'10.00 AM - 11.00 AM',
      day1:'Wednesday',
      time1:'7.00 AM - 8.00 AM',
      day1:'Thursday',
      time1:'5.00 AM - 6.00 AM',
      day1:'Friday',
      time1:'6.00 AM - 7.00 AM',
      day1:'Saturday',
      time1:'7.00 AM - 8.00 AM'
    },
    {   title:'SELF DEFENSE',
        id:2,
        img:'https://i.ibb.co/99GNwH8/baylee-gramling-5m4-Z14-SDL80-unsplash.jpg',
        description:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in',
        day1:'Monday',
        time1:'8.00 AM - 9.00 AM',
        day1:'Tuesday',
        time1:'10.00 AM - 11.00 AM',
        day1:'Wednesday',
        time1:'7.00 AM - 8.00 AM',
        day1:'Thursday',
        time1:'5.00 AM - 6.00 AM',
        day1:'Friday',
        time1:'6.00 AM - 7.00 AM',
        day1:'Saturday',
        time1:'7.00 AM - 8.00 AM'
      },
      { title:'ADVANCE GYM',
        id:3,
        img:'https://i.ibb.co/FK9B4c2/humphrey-muleba-LOA2m-Tj1vhc-unsplash.jpg',
        description:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in',
        day1:'Monday',
        time1:'8.00 AM - 9.00 AM',
        day1:'Tuesday',
        time1:'10.00 AM - 11.00 AM',
        day1:'Wednesday',
        time1:'7.00 AM - 8.00 AM',
        day1:'Thursday',
        time1:'5.00 AM - 6.00 AM',
        day1:'Friday',
        time1:'6.00 AM - 7.00 AM',
        day1:'Saturday',
        time1:'7.00 AM - 8.00 AM'
      },
      { title:'CARDIO TRAINING',
        id:4,
        img:'https://i.ibb.co/zhSQTqb/alora-griffiths-Tuzrz-Arccvc-unsplash.jpg',
        description:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in',
        day1:'Monday',
        time1:'8.00 AM - 9.00 AM',
        day1:'Tuesday',
        time1:'10.00 AM - 11.00 AM',
        day1:'Wednesday',
        time1:'7.00 AM - 8.00 AM',
        day1:'Thursday',
        time1:'5.00 AM - 6.00 AM',
        day1:'Friday',
        time1:'6.00 AM - 7.00 AM',
        day1:'Saturday',
        time1:'7.00 AM - 8.00 AM'
      },
      { title:'STRENGTH TRAINING',
        id:5,
        img:'https://i.ibb.co/yRvmnC0/john-fornander-FIu48iuo-4g-unsplash.jpg',
        description:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in',
        day1:'Monday',
        time1:'8.00 AM - 9.00 AM',
        day1:'Tuesday',
        time1:'10.00 AM - 11.00 AM',
        day1:'Wednesday',
        time1:'7.00 AM - 8.00 AM',
        day1:'Thursday',
        time1:'5.00 AM - 6.00 AM',
        day1:'Friday',
        time1:'6.00 AM - 7.00 AM',
        day1:'Saturday',
        time1:'7.00 AM - 8.00 AM'
      },
      { title:'PSYCHO TRAINING',
        id:6,
        img:'https://i.ibb.co/7Khh7yC/sven-mieke-Lx-GDv7-VA9-M-unsplash.jpg',
        description:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in',
        day1:'Monday',
        time1:'8.00 AM - 9.00 AM',
        day1:'Tuesday',
        time1:'10.00 AM - 11.00 AM',
        day1:'Wednesday',
        time1:'7.00 AM - 8.00 AM',
        day1:'Thursday',
        time1:'5.00 AM - 6.00 AM',
        day1:'Friday',
        time1:'6.00 AM - 7.00 AM',
        day1:'Saturday',
        time1:'7.00 AM - 8.00 AM'
      },
  ]
  
 
  export default Classes;